
          name: Build Alpha APK
          
          on:
            push:
              branches: [ main ]
            workflow_dispatch:
          
          jobs:
            build:
              runs-on: ubuntu-latest
          
              steps:
              - name: Checkout code
                uses: actions/checkout@v4
          
              - name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                  distribution: 'temurin'
                  java-version: 17
                  cache: gradle
          
              - name: Make gradlew executable
                run: chmod +x ./gradlew
          
              - name: Build Alpha APK
                run: ./gradlew assembleGoogleAlpha
          
              - name: Upload Alpha APK
                uses: actions/upload-artifact@v4
                with:
                  name: Alpha-APK
                  path: app/build/outputs/apk/google/alpha/*.apk
          